import type { Listing } from "@/types/listing";
import type { Room } from "@/types/room";

export const listings: Listing[] = [
  {
    id: "1",
    title: "Cedar Ridge Cabin",
    location: "Pine Harbor, Colorado",
    category: "cabin",
    section: "homes",
    imageUrl: "Pine Ridge Escape",
    imageSrc:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: true,
    isSaved: false,
    pricePerNight: 518,
    stayDuration: 2,
    rating: 4.98,
  },
  {
    id: "2",
    title: "Valley Glass House",
    location: "Riverbend, Oregon",
    category: "cabin",
    section: "homes",
    imageUrl: "Cedar Trail Lodge",
    imageSrc:
      "https://images.unsplash.com/photo-1464852045489-bccb7d17fe39?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: false,
    isSaved: true,
    pricePerNight: 271,
    stayDuration: 2,
    rating: 4.94,
  },
  {
    id: "3",
    title: "Stone Hearth Retreat",
    location: "Juniper Falls, Utah",
    category: "mansion",
    section: "homes",
    imageUrl: "Stone Hearth House",
    imageSrc:
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: true,
    isSaved: false,
    pricePerNight: 280,
    stayDuration: 2,
    rating: 4.97,
  },
  {
    id: "4",
    title: "Sunset Timber Lodge",
    location: "High Mesa, Arizona",
    category: "trending",
    section: "homes",
    imageUrl: "Twilight Chalet",
    imageSrc:
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: true,
    isSaved: true,
    pricePerNight: 410,
    stayDuration: 2,
    rating: 4.96,
  },
  {
    id: "5",
    title: "Creekside A-Frame",
    location: "Willow Glen, Washington",
    category: "cabin",
    section: "homes",
    imageUrl: "Creekside Frame",
    imageSrc:
      "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: true,
    isSaved: false,
    pricePerNight: 381,
    stayDuration: 2,
    rating: 4.99,
  },
  {
    id: "6",
    title: "Northlight Chalet",
    location: "Silver Lake, Montana",
    category: "trending",
    section: "homes",
    imageUrl: "Timberline Suite",
    imageSrc:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: true,
    isSaved: true,
    pricePerNight: 316,
    stayDuration: 2,
    rating: 4.91,
  },
  {
    id: "7",
    title: "Canopy View Villa",
    location: "Larkspur Ridge, Idaho",
    category: "mansion",
    section: "homes",
    imageUrl: "Canopy Lodge",
    imageSrc:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: false,
    isSaved: true,
    pricePerNight: 386,
    stayDuration: 2,
    rating: 4.88,
  },
  {
    id: "8",
    title: "Alder Hotel Uptown",
    location: "Chicago, Illinois",
    category: "trending",
    section: "hotels",
    imageUrl: "City Lobby",
    imageSrc:
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: false,
    isSaved: true,
    pricePerNight: 223,
    stayDuration: 2,
    rating: 4.91,
  },
  {
    id: "9",
    title: "Harborfront Hotel",
    location: "Savannah, Georgia",
    category: "beach",
    section: "hotels",
    imageUrl: "Harbor Lounge",
    imageSrc:
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: false,
    isSaved: true,
    pricePerNight: 261,
    stayDuration: 2,
    rating: 4.86,
  },
  {
    id: "10",
    title: "Riverview Inn",
    location: "New Orleans, Louisiana",
    category: "trending",
    section: "hotels",
    imageUrl: "Courtyard",
    imageSrc:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: true,
    isSaved: false,
    pricePerNight: 299,
    stayDuration: 2,
    rating: 4.92,
  },
  {
    id: "11",
    title: "Rosedale Grand",
    location: "Charleston, South Carolina",
    category: "mansion",
    section: "hotels",
    imageUrl: "Garden View",
    imageSrc:
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: false,
    isSaved: true,
    pricePerNight: 355,
    stayDuration: 2,
    rating: 4.89,
  },
  {
    id: "12",
    title: "Marigny Stay",
    location: "New Orleans, Louisiana",
    category: "beach",
    section: "hotels",
    imageUrl: "Historic Facade",
    imageSrc:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    isGuestFavorite: false,
    isSaved: true,
    pricePerNight: 312,
    stayDuration: 2,
    rating: 4.83,
  },
];

export const roomsById: Record<string, Room> = {
  "1": {
    id: "1",
    title: "Cedar Ridge Cabin",
    location: "Pine Harbor, Colorado",
    hostName: "Mia",
    hostSince: "2019",
    guestCapacity: 6,
    bedrooms: 2,
    beds: 4,
    baths: 2,
    rating: 4.93,
    reviewsCount: 142,
    description:
      "Modern cabin tucked into pines with a private deck, fire pit, and floor-to-ceiling views.",
    amenities: [
      "Hot tub",
      "Mountain view",
      "Fast Wi-Fi",
      "Indoor fireplace",
      "Washer and dryer",
      "Dedicated workspace",
    ],
    photos: [
      "Front Deck",
      "Living Room",
      "Kitchen",
      "Primary Bedroom",
      "Backyard Fire Pit",
    ],
    pricePerNight: 185,
    cleaningFee: 70,
    serviceFee: 36,
  },
  "2": {
    id: "2",
    title: "Oceanfront Retreat",
    location: "Malibu, California",
    hostName: "Noah",
    hostSince: "2017",
    guestCapacity: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    rating: 4.88,
    reviewsCount: 96,
    description:
      "Wake up to ocean views with direct beach access and a breezy open-plan living space.",
    amenities: ["Beach access", "Patio", "Wi-Fi", "Kitchen", "Parking"],
    photos: ["Balcony View", "Main Suite", "Dining", "Beach Path", "Sunset"],
    pricePerNight: 390,
    cleaningFee: 95,
    serviceFee: 58,
  },
};

export const roomIds = Object.keys(roomsById);
